### PR TITLE
Remove goerli

### PR DESCRIPTION
**Pull request by taxmeifyoucan**
Seems like most endpoints listed don't even work. It's time to get rid of it.

### CODE REVIEW

**Comment by dapplion** [comment]
LH team is attempting to rescue goerli 🙌

**Comment by parithosh** [comment]
> LH team is attempting to rescue goerli 🙌

Our nodes are still up if they can help :D

**Comment by taxmeifyoucan** [comment]
image

**Review by Karimsultan — APPROVED** [review]

**Review by barnabasbusa — APPROVED** [review]

**Comment by parithosh** [comment]
Clients have started removing the `goerli` flag in releases, So it can be assumed that goerli is now firmly in the un-supported network list and it makes sense to merge in the PR now :)

**Pull request merged**
